name: dhmcStats
main: me.botsko.dhmcstats.Dhmcstats
version: 0.2
softdepend: [PermissionsEx]
commands:
   played:
      description: Displays a player's play time on this server.
      usage: /played [player]
   player:
      description: Displays a player's stats.
      usage: /player [player]
   playerstats:
      description: Displays a few statistics of player counts.
      usage: /playerstats
   seen:
      description: Display join and last seen dates for a player.
      usage: /seen [player]
   rank:
      description: Displays rank information, mainly qualification for next rank.
      usage: /rank [player]
   rankall:
      description: Displays rank information, mainly qualification for next rank.
      usage: /rank [player]
   ison:
      description: Checks if the user is online.
      usage: /ison [player]
   scores:
      description: Checks the newmod scores of a users
      usage: /scores [player]